name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enable Corepack
        run: corepack enable
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test
